repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9021
    hooks:
      - id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
      - id: lintr

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args: [--skip=renv.lock]

  -   repo: local
      hooks:
      -   id: panache
          name: panache
          entry: panache format
          language: unsupported
          files: 'index.qmd'
